### ISSUE TITLE
args error

### ISSUE THREAD

**Issue by THU-zijun** [JiangWenPL/FisherRF#10]
Hi!
I tried to use the script bash,but get the error.

“bash scripts/lf_cfnerf.sh data/LF/statue test-lf0-statue statue”

python active_train.py -s data/LF/statue/statue -m test-lf0-statue --override_idxs statue --eval --schema=all --eval --resolution 2 --iterations 3000 --test_iterations 1000 2000 3000 --densify_until_iter=2800 --sh_up_every=1000 --sh_degree=2

[INFO]: cluster state manager is *NOT* in effect
usage: active_train.py [-h] [--sh_degree SH_DEGREE]
                       [--source_path SOURCE_PATH] [--model_path MODEL_PATH]
                       [--images IMAGES] [--resolution RESOLUTION]
                       [--white_background] [--data_device DATA_DEVICE]
                       [--eval] [--iterations ITERATIONS]
                       [--position_lr_init POSITION_LR_INIT]
                       [--position_lr_final POSITION_LR_FINAL]
                       [--position_lr_delay_mult POSITION_LR_DELAY_MULT]
                       [--position_lr_max_steps POSITION_LR_MAX_STEPS]
                       [--feature_lr FEATURE_LR] [--opacity_lr OPACITY_LR]
                       [--scaling_lr SCALING_LR] [--rotation_lr ROTATION_LR]
                       [--percent_dense PERCENT_DENSE]
                       [--lambda_dssim LAMBDA_DSSIM]
                       [--densification_interval DENSIFICATION_INTERVAL]
                       [--opacity_reset_interval OPACITY_RESET_INTERVAL]
                       [--densify_from_iter DENSIFY_FROM_ITER]
                       [--densify_until_iter DENSIFY_UNTIL_ITER]
                       [--densify_grad_threshold DENSIFY_GRAD_THRESHOLD]
                       [--convert_SHs_python] [--compute_cov3D_python]
                       [--debug] [--ip IP] [--port PORT]
                       [--debug_from DEBUG_FROM] [--detect_anomaly]
                       [--test_iterations TEST_ITERATIONS [TEST_ITERATIONS ...]]
                       [--save_iterations SAVE_ITERATIONS [SAVE_ITERATIONS ...]]
                       [--quiet]
                       [--checkpoint_iterations CHECKPOINT_ITERATIONS [CHECKPOINT_ITERATIONS ...]]
                       [--start_checkpoint START_CHECKPOINT] [--method METHOD]
                       [--schema SCHEMA] [--seed SEED]
                       [--reg_lambda REG_LAMBDA] [--I_test] [--I_acq_reg]
                       [--sh_up_every SH_UP_EVERY] [--sh_up_after SH_UP_AFTER]
                       [--min_opacity MIN_OPACITY]
                       [--filter_out_grad FILTER_OUT_GRAD [FILTER_OUT_GRAD ...]]
                       [--log_every_image]
active_train.py: error: unrecognized arguments: --override_idxs statue

sorry, I do not know why?

in the schema.py file, I found "
override_test_idxs_dict: Dict[str, List[int]] = {"basket": list(range(42, 50,2)), "africa": list(range(6, 14, 2)),
                                            "statue": list(range(68, 76, 2)), "torch": list(range(9, 17, 2))}

override_train_idxs_dict: Dict[str, List[int]] = {"basket": list(range(43, 50,2)), "africa": list(range(5, 14, 2)),
                                            "statue": list(range(67, 76, 2)), "torch": list(range(8, 17, 2))}" 
but it failed to work.

**Comment by JiangWenPL** [comment]
Thank you for pointing out. This would be fixed after the latest PR #11 gets merged into the main branch.
