### ISSUE TITLE
Pixelwise Uncertainty

### ISSUE THREAD

**Issue by tuallen** [JiangWenPL/FisherRF#2]
Thank you for your work! Do you have plans to release code for visualizing pixelwise uncertainty like in your paper?

**Comment by JiangWenPL** [comment]
We appreciate your interest in our work! We will add visualizations for uncertainty rendering after we finish our imminent deadlines. We recommend you check `colors_precomp` in the [renderer](https://github.com/JiangWenPL/FisherRF/blob/58de43ebe2d19b951ee8e464cf4dcf8c47f5e48e/gaussian_renderer/__init__.py#L90C26-L90C40) where you can replace colors_precomp with our computed Hessians scaled by depth if you need it urgently.

**Comment by tuallen** [comment]
Thank you! Did you extend the gaussian splatting codebase to get the depths?

**Comment by JiangWenPL** [comment]
Yes we do. It's also straightforward because the depth has been computed inside the CUDA Kernel but was not returned to pytorch. You can find similar implementations like this one: https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth/tree/cb65e4b86bc3bd8ed42174b72a62e8d3a3a71110
