### ISSUE TITLE
what and how set reg_lambda ?

### ISSUE THREAD

**Issue by goometasoft** [JiangWenPL/FisherRF#4]
Thank your FisherRF , i like it very much !!

can you explain what is reg_lambda ?
and how set reg_lambda ?

**Comment by JiangWenPL** [comment]
Hello, thank you for your interest in our work. $\lambda$ is mentioned in Eq.11 in our paper. Empirically we find the performance is not strongly affected by the choice of lambda. We have provided reg_lambda in our scripts for reproducibility.
