### ISSUE TITLE
(Potential bug) Regarding your Hessian computation

### ISSUE THREAD

**Issue by LinjieLyu** [JiangWenPL/FisherRF#5]
Hi. Thanks for sharing the code! I was looking at [your Hessian approximation ](https://github.com/JiangWenPL/FisherRF/blob/58de43ebe2d19b951ee8e464cf4dcf8c47f5e48e/active/H_reg.py#L51) and got confused. Here it seems like Hessian= grad(parameters). But according to the GGN method, shouldn't Hessian be J.T@J or according to the empirical Fisher approximation, grad.T @ grad. Of course, if you do the diagonal, I assume this will be something like grad**2.

Does this make sense?  Thank you.

**Comment by tuallen** [comment]
My team noticed this as well. It appears the code computes the gradient instead of the diagonal of the Hessian.

**Comment by JiangWenPL** [comment]
Thank you for your interest in our work. We modified the computation inside the CUDA kernel and only use .grad as a proxy to return the results.

**Comment by LinjieLyu** [comment]
I see. That is brilliant. If I understand correctly, your modified gradient is $\sum_{i} Jacobian[i][j]^2$ while the original gradient is $\sum_{i} Jacobian[i][j] $. Is that right?

**Comment by JiangWenPL** [comment]
Yes that's the case after we refactored the backward pipeline.

**Comment by Shubhendu-Jena** [comment]
Hi, will it also be possible to obtain the Hessian by doing grad.T @ grad without changing the cuda kernel in the original 3dgs code, or is there something wrong with this?

**Comment by JiangWenPL** [comment]
It will be inaccurate because grad is an Mx1 vector where M is the number of parameters whereas we wish to compute the sum of diagonal matrix $J^T  J$ where J is of shape $N\times M$, where N is the number of output of renderings.
