### ISSUE TITLE
Negative variance for 3DGS rotation

### ISSUE THREAD

**Issue by LinjieLyu** [JiangWenPL/FisherRF#6]
Hi there. I was trying to evaluate the [diag(Hessian)](https://github.com/JiangWenPL/FisherRF/blob/58de43ebe2d19b951ee8e464cf4dcf8c47f5e48e/active/H_reg.py#L51) for 3DGS parameters on the NeRF Lego sequence. I understand you hack into the CUDA kernel so the grad here should be the diagonal of Hessian (sum of squares). And I assume they are no less than 0.

However when I output the max and min for each p.grad I find 
***
xyz: tensor(3917212.2500, device='cuda:0') tensor(0., device='cuda:0') [29/02 15:14:06]
rgb: tensor(20.5388, device='cuda:0') tensor(0., device='cuda:0') [29/02 15:14:06]
sh: tensor(51.0888, device='cuda:0') tensor(0., device='cuda:0') [29/02 15:14:06]
scale: tensor(8684.0762, device='cuda:0') tensor(0., device='cuda:0') [29/02 15:14:06]
rotation: tensor(11629.0010, device='cuda:0') tensor(-119.9005, device='cuda:0') [29/02 15:14:06]
opacity: tensor(36.8370, device='cuda:0') tensor(0., device='cuda:0') [29/02 15:14:06]
***
It seems like your Hessian w.r.t.  rotation has negative values. I notice by default the 'rotation' is filtered out.  Is there a reason for this?

Thank you.

**Comment by JiangWenPL** [comment]
It's because the quaternion was normalized before feeding into the CUDA kernel. We filtered out the diagonal Hessians as a quick fix when rushing for the deadline.

**Comment by JIANG-CX** [comment]
> It's because the quaternion was normalized before feeding into the CUDA kernel. We filtered out the diagonal Hessians for rotation as a quick fix when rushing for the deadline.

Hi! If considering the rotation, will it can achieve better performance?
